require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'example' do
  # Pods for example
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  target 'exampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'example-tvOS' do
  # Pods for example-tvOS

  target 'example-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
